name: ffuf
tags:
   - http
target: service
service: http, http-proxy # From nmap
   # or
#   - target: port
#   - port 445
cmd: ffuf -u http://<target>/FUZZ -w <wordlist> -o /tmp/<randstring> 1>&2 && cat /tmp/<randstring>
variable:
   wordlist: /tmp/wordlist 
#regex:
#   - .* ... .*
#   - 2.*
#regexSuccess: "Anonymous connection allowed"
# Function parserSmbMap called when command executed
parserFunction: ParseFfuf