name: ffuf
tags:
   - http
   - https
target: service
service: http # From nmap
   # or
#   - target: port
#   - port 445
cmd: ffuf -u http://<target>/FUZZ -p <wordlist>
variable:
   wordlist: /usr/share/SecLists/Discovery/Web-Content/directory-list-2.3-medium.txt 
#regex:
#   - .* ... .*
#   - 2.*
#regexSuccess: "Anonymous connection allowed"
# Function parserSmbMap called when command executed
parserFunction: ParseFfuf