name: nmap quick scan
tags: 
   - nmap
   - scan
   - quick
target: network, host
cmd: nmap --top-port 1000 -oX - <target> -sC
# Function parserNmap called when command executed
parserFunction: ParseNmap