name: smbmap
tags:
   - smb
target: service
service: 
   netbios-ssn: smbmap -H <target> --no-update
   # or
#   - target: port
#   - port 445
# Function parserSmbMap called when command executed
parserFunction: ParseSmbmap