name: nuclei
description: Use the enumeration template of nuclei to find juicy information
tags:
   - http
target: service
#service: http, http-proxy # From nmap
service:
   http: 
      variable:
         protocol: http
   http-alt: 
        variable:
         protocol: http
   http-proxy: 
      variable:
         protocol: http
   ssl/https: 
      variable:
         protocol: https
 # or
#   - target: port
#   - port: 445
cmd: nuclei -u <protocol>://<target>:<port> -t fuzzing -t default-logins -t dns -t exposed-panels -t exposures -t fuzzing -t iot -t miscellaneous -t misconfiguration -t network -t takeovers -t technologies  -tags "",tech,takeover,network,disclosure,unauth,drupal,apache,misconfig,config,thinkcmf,aem,ssrf,logs,debug,exposure,enum,gitlab,misc,sqlite,aws,cgi,injection,gitlab,fileupload,docker,servicenow,iot,panel,dns,default-login,fuzz,lfi,phpmyadmin -json 
parserFunction: ParseNuclei