name: smbmap
description: Use smbmap to detect anonymous connection 
tags:
   - smb
target: service
service: 
   microsoft-ds:
      variable:
   # or
#   - target: port
#   - port 445
cmd: smbmap -H <target> -P <port> --no-update --no-color
# Function parserSmbMap called when command executed
parserFunction: ParseSmbmap
printFunction: PrintOutputSmbMap