name: ffuf
description: Enumerate directory with ffuf
tags:
   - http
target: service
#service: http, http-proxy # From nmap
service:
   http: 
      variable:
         protocol: http
   http-alt: 
        variable:
         protocol: http
   http-proxy: 
      variable:
         protocol: http
   ssl/https: 
      variable:
         protocol: https
   # or
#   - target: port
#   - port: 445
cmd: ffuf -u <protocol>://<target>:<port>/FUZZ -w <wordlist> -o /tmp/<randstring> 1>&2 && cat /tmp/<randstring>
variable:
   wordlist: /tmp/wordlist 
#regex:
#   - .* ... .*
#   - 2.*
#regexSuccess: "Anonymous connection allowed"
parserFunction: ParseFfuf